import 'package:flutter/material.dart';
import '../widgets/app_drawer.dart';
import '../services/firestore_service.dart';
import '../models/resource_model.dart';

class ResourceTrackerScreen extends StatefulWidget {
  const ResourceTrackerScreen({super.key});

  @override
  State<ResourceTrackerScreen> createState() => _ResourceTrackerScreenState();
}

class _ResourceTrackerScreenState extends State<ResourceTrackerScreen> {
  static const List<String> _units = ['kg', 'g', 'L', 'ml', 'pcs', 'boxes', 'packs'];
  
  void _addResource() {
    final nameCtrl = TextEditingController();
    final qtyCtrl = TextEditingController();
    String selectedUnit = _units.first;
    bool isSaving = false;

    showDialog(
      context: context,
      builder: (ctx) => StatefulBuilder(
        builder: (context, setState) => AlertDialog(
          title: const Text('Add New Resource'),
          content: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                TextField(
                  controller: nameCtrl,
                  decoration: const InputDecoration(labelText: 'Resource Name (e.g. Water)'),
                ),
                const SizedBox(height: 8),
                TextField(
                  controller: qtyCtrl,
                  decoration: const InputDecoration(labelText: 'Quantity'),
                  keyboardType: TextInputType.number,
                ),
                const SizedBox(height: 8),
                DropdownButtonFormField<String>(
                  value: selectedUnit,
                  decoration: const InputDecoration(labelText: 'Unit'),
                  items: _units
                      .map((u) => DropdownMenuItem(value: u, child: Text(u)))
                      .toList(),
                  onChanged: (v) {
                    if (v != null) {
                      setState(() => selectedUnit = v);
                    }
                  },
                ),
              ],
            ),
          ),
          actions: [
            TextButton(onPressed: isSaving ? null : () => Navigator.pop(ctx), child: const Text('Cancel')),
            ElevatedButton(
              onPressed: isSaving
                  ? null
                  : () async {
                      final name = nameCtrl.text.trim();
                      final qty = int.tryParse(qtyCtrl.text.trim()) ?? 0;

                      if (name.isEmpty || qty <= 0) {
                        if (context.mounted) {
                          ScaffoldMessenger.of(context).showSnackBar(
                            const SnackBar(content: Text('Enter a name and quantity > 0')),
                          );
                        }
                        return;
                      }

                      setState(() => isSaving = true);
                      try {
                        final newItem = ResourceModel(
                          id: '', // Generated by Firestore
                          name: name,
                          quantity: qty,
                          imageUrl: '',
                          unit: selectedUnit,
                        );

                        await FirestoreService.instance.addResource(newItem);
                        if (context.mounted) {
                          Navigator.pop(ctx);
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(content: Text('Saved "$name" to resources')),
                          );
                        }
                      } catch (e) {
                        if (context.mounted) {
                          String msg = 'Failed to save resource: $e';
                          if (e.toString().contains('permission-denied')) {
                            msg = 'Upload blocked by Firebase Storage rules. Allow authenticated writes or relax rules for resources.';
                          }
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(content: Text(msg), backgroundColor: Colors.red),
                          );
                        }
                      } finally {
                        if (context.mounted) {
                          setState(() => isSaving = false);
                        }
                      }
                    },
              child: isSaving
                  ? const SizedBox(width: 18, height: 18, child: CircularProgressIndicator(strokeWidth: 2))
                  : const Text('Add'),
            )
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Resource Tracker')),
      drawer: const AppDrawer(),
      body: Padding(
        padding: const EdgeInsets.all(12.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            const Text('Inventory', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            Expanded(
              child: StreamBuilder<List<ResourceModel>>(
                stream: FirestoreService.instance.streamResources(),
                builder: (context, snapshot) {
                  if (snapshot.hasError) return Center(child: Text('Error: ${snapshot.error}'));
                  if (snapshot.connectionState == ConnectionState.waiting) {
                    return const Center(child: CircularProgressIndicator());
                  }
                  
                  final items = snapshot.data ?? [];
                  if (items.isEmpty) {
                    return const Center(child: Text('No resources available. Add some!'));
                  }

                  return ListView.builder(
                    itemCount: items.length,
                    itemBuilder: (context, idx) {
                      final item = items[idx];
                      return Card(
                        margin: const EdgeInsets.symmetric(vertical: 6),
                        child: ListTile(
                          leading: SizedBox(
                            width: 50,
                            height: 50,
                            child: item.imageUrl.isNotEmpty
                                ? Image.network(
                                    item.imageUrl, 
                                    fit: BoxFit.cover,
                                    errorBuilder: (_,__,___) => const Icon(Icons.broken_image),
                                  )
                                : const Icon(Icons.inventory_2),
                          ),
                          title: Text(item.name, style: const TextStyle(fontWeight: FontWeight.bold)),
                          subtitle: Text('Quantity: ${item.quantity} ${item.unit}'),
                          trailing: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              IconButton(
                                icon: const Icon(Icons.remove_circle_outline, color: Colors.orange),
                                onPressed: () {
                                  if (item.quantity > 0) {
                                    FirestoreService.instance.updateResourceQuantity(item.id, item.quantity - 1).catchError((e) {
                                      if (context.mounted) {
                                        ScaffoldMessenger.of(context).showSnackBar(
                                          SnackBar(content: Text('Failed to update resource: $e'), backgroundColor: Colors.red),
                                        );
                                      }
                                    });
                                  }
                                },
                              ),
                              IconButton(
                                icon: const Icon(Icons.add_circle_outline, color: Colors.green),
                                onPressed: () {
                                  FirestoreService.instance.updateResourceQuantity(item.id, item.quantity + 1).catchError((e) {
                                    if (context.mounted) {
                                      ScaffoldMessenger.of(context).showSnackBar(
                                        SnackBar(content: Text('Failed to update resource: $e'), backgroundColor: Colors.red),
                                      );
                                    }
                                  });
                                },
                              ),
                              IconButton(
                                icon: const Icon(Icons.delete, color: Colors.red),
                                onPressed: () => _confirmDelete(item),
                              ),
                            ],
                          ),
                        ),
                      );
                    },
                  );
                },
              ),
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _addResource,
        tooltip: 'Add resource',
        child: const Icon(Icons.add_shopping_cart),
      ),
    );
  }

  void _confirmDelete(ResourceModel item) {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Delete Resource'),
        content: Text('Remove ${item.name} from inventory?'),
        actions: [
          TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Cancel')),
          ElevatedButton(
            style: ElevatedButton.styleFrom(backgroundColor: Colors.red, foregroundColor: Colors.white),
            onPressed: () async {
              try {
                await FirestoreService.instance.deleteResource(item.id);
                if (context.mounted) {
                  Navigator.pop(ctx);
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(content: Text('Deleted ${item.name}')),
                  );
                }
              } catch (e) {
                if (context.mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(content: Text('Failed to delete resource: $e'), backgroundColor: Colors.red),
                  );
                }
              }
            },
            child: const Text('Delete'),
          )
        ],
      ),
    );
  }
}
